name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-go-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'plugin-go-backend/desktop/go.mod'
          cache-dependency-path: |
            plugin-go-backend/desktop/go.sum
            plugin-go-backend/shared/go.sum
            plugin-go-backend/mobile/go.sum
      
      - name: Set up protoc
        uses: arduino/setup-protoc@v3
        with:
          version: '28.x'
          repo-token: ${{ github.token }}

      - name: Install Task
        uses: go-task/setup-task@v1

      # TODO: run in a separate job with matrix for platforms
      # - name: Compile Go backend
      #   run: task backend:build

      - name: Run Go tests
        run: task backend:test

  test-js-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - uses: oven-sh/setup-bun@v2
      
      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Type check
        run: task api:typecheck

      - name: Build
        run: task api:build

  test-rust-core:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          # - windows-latest # TODO: reenable (too slow currently)
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set up protoc
        uses: arduino/setup-protoc@v3
        with:
          version: '28.x'
          repo-token: ${{ github.token }}

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: install webkit2gtk
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1

      - name: Run tests
        run: task core:test

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'plugin-go-backend/desktop/go.mod'
          cache-dependency-path: |
            plugin-go-backend/desktop/go.sum
            plugin-go-backend/shared/go.sum
            plugin-go-backend/mobile/go.sum

      - name: Set up protoc
        uses: arduino/setup-protoc@v3
        with:
          version: '28.x'
          repo-token: ${{ github.token }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1 libgtk-3-dev

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Run integration tests
        run: task test-integration
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: 1
